name: .NET Core CI

# Executed on push and pull on branch main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set .NET version
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Restore NuGet packages
      - name: Restore dependencies
        run: dotnet restore

      # Build projects
      - name: Build
        run: dotnet build --no-restore

      # Run tests
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
